export const CARDS = [
  {
    id: "a",
    label: "Карточка 1",
    placeholder: "🦊",
    hue: 18,
    image: "../images/img1.png",
  },
  {
    id: "b",
    label: "Карточка 2",
    placeholder: "🐙",
    hue: 330,
    image: "../images/img2.png",
  },
  {
    id: "c",
    label: "Карточка 3",
    placeholder: "🌵",
    hue: 140,
    image: "../images/img3.png",
  },
  {
    id: "d",
    label: "Карточка 4",
    placeholder: "🚀",
    hue: 220,
    image: "../images/img4.png",
  },
  {
    id: "e",
    label: "Карточка 5",
    placeholder: "🍉",
    hue: 350,
    image: "../images/img5.png",
  },
  {
    id: "f",
    label: "Карточка 6",
    placeholder: "🎧",
    hue: 275,
    image: "../images/img6.png",
  },
  {
    id: "g",
    label: "Карточка 7",
    placeholder: "🌙",
    hue: 50,
    image: "../images/img7.png",
  },
  {
    id: "h",
    label: "Карточка 8",
    placeholder: "🧊",
    hue: 190,
    image: "../images/img8.png",
  },
];
